/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IEEEP1451PROJECT_H
#define IEEEP1451PROJECT_H

/* function declarations */
void init_ieeeP1451Project(void);
Netsnmp_Node_Handler handle_seTemperature;
Netsnmp_Node_Handler handle_seHumidity;
Netsnmp_Node_Handler handle_seDistence;
Netsnmp_Node_Handler handle_seAcceleration;
Netsnmp_Node_Handler handle_seHS;
Netsnmp_Node_Handler handle_seSmoker;
Netsnmp_Node_Handler handle_seGravity;
Netsnmp_Node_Handler handle_sePressure;
Netsnmp_Node_Handler handle_acLamp;
Netsnmp_Node_Handler handle_acHunidifier;
Netsnmp_Node_Handler handle_acbuzzer;
Netsnmp_Node_Handler handle_acLEDScreen;

#endif /* IEEEP1451PROJECT_H */
