/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IEEEP1451PROJECT_H
#define IEEEP1451PROJECT_H

/* function declarations */
void init_ieeeP1451Project(void);
Netsnmp_Node_Handler handle_SeTemperature;
Netsnmp_Node_Handler handle_SeLight;
Netsnmp_Node_Handler handle_SeHumidity;
Netsnmp_Node_Handler handle_SeDistence;
Netsnmp_Node_Handler handle_SeAccelerationx;
Netsnmp_Node_Handler handle_SeAccelerationy;
Netsnmp_Node_Handler handle_SeAccelerationz;
Netsnmp_Node_Handler handle_SeHS;
Netsnmp_Node_Handler handle_SeLoadVoltage;
Netsnmp_Node_Handler handle_SeLoadCurrent;
Netsnmp_Node_Handler handle_SeLoadPower;
Netsnmp_Node_Handler handle_SePressure;
Netsnmp_Node_Handler handle_SeFree1;
Netsnmp_Node_Handler handle_SeFree2;
Netsnmp_Node_Handler handle_AcLamp;
Netsnmp_Node_Handler handle_AcHunidifier;
Netsnmp_Node_Handler handle_Acbuzzer;
Netsnmp_Node_Handler handle_AcLEDScreen;
Netsnmp_Node_Handler handle_AcFree1;
Netsnmp_Node_Handler handle_AcFree2;

void init_ieeeP1451Project(void);
void initialize_table_ieeeP1451TimTable(void);
Netsnmp_Node_Handler ieeeP1451TimTable_handler;
Netsnmp_First_Data_Point  ieeeP1451TimTable_get_first_data_point;
Netsnmp_Next_Data_Point   ieeeP1451TimTable_get_next_data_point;

/* column number definitions for table ieeeP1451TimTable */
       #define COLUMN_TIMID		1
       #define COLUMN_CHANNELID		2
       #define COLUMN_COMMUTYPE		3
       #define COLUMN_COMMUADDRESS		4
       #define COLUMN_TESTVALUE		5
       #define COLUMN_P1451ROWSTATUS		6
#endif /* IEEEP1451PROJECT_H */
