/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "TestTraps.h"

extern const oid snmptrap_oid[] = {1,3,6,1,4,1,1000,1,1,1,0};
extern const size_t snmptrap_oid_len;

void init_TestTraps(void)
{
  DEBUGMSGTL(("TestTraps","Initializing\n"));
  snmp_alarm_register(5,SA_REPEAT,read_cpudata_repeat, NULL);
}


int
send_cpuRatioHigh_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid cpuRatioHigh_oid[] = { 1,3,6,1,4,1,1000,1,1 };
    const oid SystemTrapDescription_oid[] = { 1,3,6,1,4,1,1000,1,1,2, 0 };
    const oid TestTrapDescription_oid[] = { 1,3,6,1,4,1,1000,1,1,3, 0 };
    static char TestTrapDescription[50];
    strcpy(TestTrapDescription,"CPU使用率过高");

    /*
     * Set the snmpTrapOid.0 value
     */
    //status = snmp_add_var(pdu, oid_cpu_Alarm, OID_LENGTH(oid_cpu_Alarm), ‘s’, “cpu Alarming”);
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        's',“cpu Alarming”);
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        SystemTrapDescription_oid, OID_LENGTH(SystemTrapDescription_oid),
        ,
        /* Set an appropriate value for SystemTrapDescription */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}

void judge_send_cputrap(int cpu)
{
    static unsigned int cputrap_clientreg = 0;
    if(cpu > 80)
    {
        if(cputrap_clientreg == 0)
        {
             send_cpuRatioHigh_trap();
             cputrap_clientreg = snmp_alarm_register(5,SA_REPEAT,send_cpuRatioHigh_trap,NULL);
           // snmp_alarm_register(5,SA_REPEAT,send_trap2, NULL);
        }
    }
    else
    {
        if(cputrap_clientreg != 0)
        {
            snmp_alarm_unregister(cputrap_clientreg);
            cputrap_clientreg = 0;
        }

    }
}

void read_cpudata_repeat(unsigned int clientreg, void *clientarg)
{
    int cpu = 90;
    judge_send_cputrap(cpu);
}


void init_alarm_info(void)
{
    DEBUGMSGTL((“dcsserver”,
    “initializing (setting callback alarm)\n”));
    //CDcsRunConfigManager *serverInfo = CDcsRunConfigManager::GetInstance();
    snmp_alarm_register(5,/*serverInfo->GetTrapTimeSpan();*/ /* seconds, 秒 */
    SA_REPEAT, /* repeat (every 30 seconds). 每隔30秒发送一个trap */
    send_trap2, /* our callback 我们的回调函数 */
    NULL /* no callback data needed */
    );
}
void send_trap2(unsigned int clientreg, void *clientarg)
{
    //MIB Tree中需要trap的报警节点节点主动trap的用./././././././2./
    static oid oid_cpu_Alarm[] = {1, 3, 6, 1, 4, 1, 9000, 2, 1 };
    static oid oid_memory_Alarm[] = {1, 3, 6, 1, 4, 1, 9000, 2, 2 };
    static oid oid_disk_Alarm[] = {1, 3, 6, 1, 4, 1, 9000, 2, 3 };
    netsnmp_pdu *pdu;
    int status = 0;
    // create pdu
    pdu = snmp_pdu_create(SNMP_MSG_TRAP2); //SNMP_MSG_TRAP
    if ( !pdu )
    {
        CDcslog::GetInstance()->dlog_error(“send_trap Failed to create trap PDU”);
        return;
    }
    if(status != 0)
    {
        CDcslog::GetInstance()->dlog_error(“send_trap snmp_add_var() error”);
        snmp_free_pdu(pdu);
        return;                                                         
    }
//SNMPV2 版本2
     status = create_trap_session(“127.0.0.1″, SNMP_TRAP_PORT, “public”, SNMP_VERSION_2c, SNMP_MSG_TRAP2);
//SNMPV1 第二个参数为SNMP_TRAP_PORT时有警告，应该为0
    //status = create_trap_session(DEFAULT_ADDR, 0, “public”, SNMP_VERSION_1, SNMP_MSG_TRAP);
//第二个参数为SNMP_TRAP_PORT时有警告，应该为0
    if (status == 0)
    {
        CDcslog::GetInstance()->dlog_error(“send_trap create_trap_session() error”);
        snmp_free_pdu(pdu);
        return;
    }
//在这里添加要发送的变量，可以添加发送的逻辑
bool flag =false;
//cpu利用率大于85%时，添加到trap列表中
if ( GetUsedCPU()>85)
{
    flag = true;
    status = snmp_add_var(pdu, oid_cpu_Alarm, OID_LENGTH(oid_cpu_Alarm), ‘s’, “cpu Alarming”);
}
//memory
if ( GetUsedMemory()>85)
{
    flag = true;
    status = snmp_add_var(pdu, oid_memory_Alarm, OID_LENGTH(oid_memory_Alarm), ‘s’, “memory Alarming”);
}
//disk:c:
if ( GetUsedDisk()>85)
{
    flag = true;
    status = snmp_add_var(pdu, oid_disk_Alarm, OID_LENGTH(oid_disk_Alarm), ‘s’, “disk Alarming”);
}
//列表中有内容，则发送
if (flag)
{
    send_trap_vars(1, 0, pdu->variables);
}
//释放资源
snmpd_free_trapsinks();
snmp_free_pdu(pdu);
}