/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "TestTraps.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_cpuRatioHigh_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid cpuRatioHigh_oid[] = { 1,3,6,1,4,1,1000,1,1 };
    const oid SystemTrapDescription_oid[] = { , /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        cpuRatioHigh_oid, sizeof(cpuRatioHigh_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        SystemTrapDescription_oid, OID_LENGTH(SystemTrapDescription_oid),
        ,
        /* Set an appropriate value for SystemTrapDescription */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
