/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IEEEP1451PROJECT_H
#define IEEEP1451PROJECT_H

/* function declarations */
void init_ieeeP1451Project(void);
Netsnmp_Node_Handler handle_seTemperature;
Netsnmp_Node_Handler handle_seLight;
Netsnmp_Node_Handler handle_acLamp;
Netsnmp_Node_Handler handle_acHumidifier;
Netsnmp_Node_Handler handle_acLcd;

#endif /* IEEEP1451PROJECT_H */