/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef IEEEP1451PROJECT_H
#define IEEEP1451PROJECT_H

/* function declarations */
void init_ieeeP1451Project(void);
void initialize_table_ieeeP1451TimTable(void);
Netsnmp_Node_Handler ieeeP1451TimTable_handler;
Netsnmp_First_Data_Point  ieeeP1451TimTable_get_first_data_point;
Netsnmp_Next_Data_Point   ieeeP1451TimTable_get_next_data_point;
NetsnmpCacheLoad ieeeP1451TimTable_load;
NetsnmpCacheFree ieeeP1451TimTable_free;
#define IEEEP1451TIMTABLE_TIMEOUT  60

/* column number definitions for table ieeeP1451TimTable */
       #define COLUMN_TIMID		1
       #define COLUMN_CHANNELID		2
       #define COLUMN_COMMUTYPE		3
       #define COLUMN_COMMUADDRESS		4
       #define COLUMN_TESTVALUE		5
       #define COLUMN_P1451ROWSTATUS		6
#endif /* IEEEP1451PROJECT_H */
