/* 
* Note: this file originally auto-generated by mib2c using 
*        $ 
*/  
  
#include <net-snmp/net-snmp-config.h>  
#include <net-snmp/net-snmp-includes.h>  
#include <net-snmp/agent/net-snmp-agent-includes.h>  
#include "TestTraps.h"  
  
void read_cpudata_repeat(unsigned int clientreg, void *clientarg);  
extern const oid snmptrap_oid[] = {1, 3, 6, 1, 4, 1, 1000, 1, 0, 1};  
extern const size_t snmptrap_oid_len = OID_LENGTH(snmptrap_oid);  
  
void init_TestTraps(void)  
{  
	DEBUGMSGTL(("TestTrap","Initializing\n"));  
	snmp_alarm_register(1,SA_REPEAT,read_cpudata_repeat, NULL); // (秒，重复，回调函数名，不需要回调数据) 
}  
  
int  
send_cpuRatioHigh_trap(void)  
{  
	netsnmp_variable_list *var_list = NULL;  
	const oid       cpuRatioHigh_oid[] = { 1, 3, 6, 1, 4, 1, 1000, 1, 1,1,0 }; 
	size_t cpuRatioHigh_oid_len = OID_LENGTH(cpuRatioHigh_oid); 
	const oid       SystemTrapDescription_oid[] ={ 1,3,6,1,4,1,1000,1,2,1, 0 };
	size_t SystemTrapDescription_oid_len = OID_LENGTH(SystemTrapDescription_oid);
	  
	static char TestTrapDescription[50];  
	strcpy(TestTrapDescription,"CPU使用率过高");  
	/* 
	* Set the snmpTrapOid.0 value 
	*/  
	snmp_varlist_add_variable(&var_list,  
	cpuRatioHigh_oid, cpuRatioHigh_oid_len,  
	ASN_OBJECT_ID,  
	(u_char *) snmptrap_oid,
	 sizeof(snmptrap_oid));  
	  
	/* 
	* Add any objects from the trap definition 
	*/  
	snmp_varlist_add_variable(&var_list,  
	SystemTrapDescription_oid,  
	OID_LENGTH(SystemTrapDescription_oid),  
	ASN_OCTET_STR,  
	/* 
	* Set an appropriate value for SystemTrapDescription 
	*/  
	TestTrapDescription, strlen(TestTrapDescription));  
	  
	/* 
	* Add any extra (optional) objects here 
	*/  
	  
	/* 
	* Send the trap to the list of configured destinations 
	*  and clean up 
	*/  
	send_v2trap(var_list);  
	snmp_free_varbind(var_list);  
  
	return SNMP_ERR_NOERROR;  
}  
void judge_send_cputrap(int cpu)  
{  
	static unsigned int cputrap_clientreg = 0;  
	if(cpu > 80)  
	{  
		if(cputrap_clientreg == 0){  
			//send_cpuRatioHigh_trap();  
			cputrap_clientreg = snmp_alarm_register(5,SA_REPEAT,send_cpuRatioHigh_trap,NULL);  
		  
		}  
	}  
	else  
	{  
		if(cputrap_clientreg != 0)  
		{  
			snmp_alarm_unregister(cputrap_clientreg);  
			cputrap_clientreg = 0;  
		}  
	}  
}  
  
void read_cpudata_repeat(unsigned int clientreg, void *clientarg)  
{  
	int cpu = 90;  
	judge_send_cputrap(cpu);  
}  