/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IEEEP1451PROJECT_H
#define IEEEP1451PROJECT_H

/* function declarations */
void init_ieeeP1451Project(void);
Netsnmp_Node_Handler handle_SeTemperature;
Netsnmp_Node_Handler handle_SeLight;
Netsnmp_Node_Handler handle_SeHumidity;
Netsnmp_Node_Handler handle_SeDistence;
Netsnmp_Node_Handler handle_SeAccelerationx;
Netsnmp_Node_Handler handle_SeAccelerationy;
Netsnmp_Node_Handler handle_SeAccelerationz;
Netsnmp_Node_Handler handle_SeHS;
Netsnmp_Node_Handler handle_SeLoadVoltage;
Netsnmp_Node_Handler handle_SeLoadCurrent;
Netsnmp_Node_Handler handle_SeLoadPower;
Netsnmp_Node_Handler handle_SePressure;
Netsnmp_Node_Handler handle_SeFree1;
Netsnmp_Node_Handler handle_SeFree2;
Netsnmp_Node_Handler handle_AcLamp;
Netsnmp_Node_Handler handle_AcHunidifier;
Netsnmp_Node_Handler handle_Acbuzzer;
Netsnmp_Node_Handler handle_AcLEDScreen;
Netsnmp_Node_Handler handle_AcFree1;
Netsnmp_Node_Handler handle_AcFree2;
Netsnmp_Node_Handler handle_Getfloors;
Netsnmp_Node_Handler handle_GetStatusofDoor;
Netsnmp_Node_Handler handle_GetStatusofLamp;
Netsnmp_Node_Handler handle_Getfree1;
Netsnmp_Node_Handler handle_Getfree2;
Netsnmp_Node_Handler handle_Getfree3;
Netsnmp_Node_Handler handle_Getfree4;
Netsnmp_Node_Handler handle_Getfree5;
Netsnmp_Node_Handler handle_Getfree6;
Netsnmp_Node_Handler handle_Getfree7;
Netsnmp_Node_Handler handle_Setfloors;
Netsnmp_Node_Handler handle_SetStateofDoor;
Netsnmp_Node_Handler handle_Setfree1;
Netsnmp_Node_Handler handle_Setfree2;
Netsnmp_Node_Handler handle_Setfree3;
Netsnmp_Node_Handler handle_Setfree4;
Netsnmp_Node_Handler handle_Setfree5;
Netsnmp_Node_Handler handle_Setfree6;
Netsnmp_Node_Handler handle_Setfree7;

#endif /* IEEEP1451PROJECT_H */
